dataset_root: prod_datasets/detection/v2_25class
data_yaml: prod_datasets/detection/v2_25class/data.yaml
model: yolo11m.pt
project_name: reciclamack_local
run_name: v2_25class_macos_512_yolo11m
output_root: model_pipeline/artifacts/detection_training

training:
  device: auto
  epochs: 80
  imgsz: 512
  batch: 4
  patience: 20
  workers: 2
  cache: false

export:
  dynamic: false
  opset: 17
