#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import math
from collections import Counter
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prioritize review_queue.csv into ranked batches.")
    parser.add_argument(
        "--review-queue",
        type=Path,
        required=True,
        help="Path to review_queue.csv generated by build_unified_dataset.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory to write review_priority and batch files.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=60,
        help="Number of rows per batch file.",
    )
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def score_rows(rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    if not rows:
        return []

    by_source = Counter(r.get("source_dataset", "") for r in rows)
    by_reason = Counter(r.get("reason", "") for r in rows)
    by_dedup = Counter(r.get("dedup_group_id", "") for r in rows)

    max_source = max(by_source.values()) if by_source else 1
    max_reason = max(by_reason.values()) if by_reason else 1
    max_group = max(by_dedup.values()) if by_dedup else 1

    scored: list[dict[str, Any]] = []
    for row in rows:
        src = row.get("source_dataset", "")
        reason = row.get("reason", "")
        dedup = row.get("dedup_group_id", "")
        size = int(row.get("file_size", "0") or 0)
        width = int(row.get("width", "0") or 0)
        height = int(row.get("height", "0") or 0)

        # Higher impact first:
        # - larger repeated dedup groups (one decision informs many similar items)
        # - underrepresented sources (early cross-source validation)
        # - dominant reason groups (quickly reduces queue uncertainty)
        # - larger resolution/file-size as secondary signal for easier review confidence
        dedup_component = by_dedup[dedup] / max_group
        source_component = (max_source / by_source[src]) if by_source[src] else 0.0
        reason_component = by_reason[reason] / max_reason
        size_component = math.log10(max(size, 1) + 1) / 5.0
        pixel_component = math.log10(max(width * height, 1) + 1) / 6.0

        score = (
            60.0 * dedup_component
            + 20.0 * source_component
            + 10.0 * reason_component
            + 5.0 * size_component
            + 5.0 * pixel_component
        )

        out = dict(row)
        out["priority_score"] = round(score, 4)
        out["dedup_group_count"] = by_dedup[dedup]
        out["source_queue_count"] = by_source[src]
        out["reason_queue_count"] = by_reason[reason]
        scored.append(out)

    scored.sort(
        key=lambda r: (
            -float(r["priority_score"]),
            -int(r["dedup_group_count"]),
            r.get("source_dataset", ""),
            r.get("source_relpath", ""),
        )
    )
    return scored


def main() -> None:
    args = parse_args()
    rows = read_csv(args.review_queue)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    scored = score_rows(rows)
    if not scored:
        write_csv(args.output_dir / "review_priority.csv", [], [])
        print("No review rows found.")
        return

    base_fields = list(rows[0].keys())
    extra = [
        "priority_score",
        "dedup_group_count",
        "source_queue_count",
        "reason_queue_count",
        "priority_rank",
        "batch_id",
        "batch_rank",
    ]
    fields = base_fields + extra

    total = len(scored)
    batch_size = max(1, args.batch_size)
    for idx, row in enumerate(scored, start=1):
        batch_num = ((idx - 1) // batch_size) + 1
        batch_rank = ((idx - 1) % batch_size) + 1
        row["priority_rank"] = idx
        row["batch_id"] = f"batch_{batch_num:02d}"
        row["batch_rank"] = batch_rank

    write_csv(args.output_dir / "review_priority.csv", fields, scored)

    num_batches = ((total - 1) // batch_size) + 1
    for batch_num in range(1, num_batches + 1):
        batch_id = f"batch_{batch_num:02d}"
        batch_rows = [r for r in scored if r["batch_id"] == batch_id]
        write_csv(args.output_dir / f"{batch_id}.csv", fields, batch_rows)

    # Small summary for quick actioning.
    by_source = Counter(r.get("source_dataset", "") for r in scored)
    by_reason = Counter(r.get("reason", "") for r in scored)
    summary_lines = [
        "# Review Batches Summary",
        "",
        f"- Total review items: {total}",
        f"- Batch size: {batch_size}",
        f"- Number of batches: {num_batches}",
        "",
        "## Counts by Source",
    ]
    for src, count in sorted(by_source.items(), key=lambda x: (-x[1], x[0])):
        summary_lines.append(f"- {src}: {count}")
    summary_lines.append("")
    summary_lines.append("## Counts by Reason")
    for reason, count in sorted(by_reason.items(), key=lambda x: (-x[1], x[0])):
        summary_lines.append(f"- {reason}: {count}")
    summary_lines.append("")
    summary_lines.append("## Next Step")
    summary_lines.append("- Start with `batch_01.csv` and record final decision per row (`televisao` vs `monitor`/`negative`).")
    (args.output_dir / "review_batches_summary.md").write_text(
        "\n".join(summary_lines), encoding="utf-8"
    )

    print(f"Prioritized rows: {total}")
    print(f"Batches created: {num_batches}")
    print(f"Output: {(args.output_dir / 'review_priority.csv').as_posix()}")


if __name__ == "__main__":
    main()

